# Generated by Django 6.0.1 on 2026-01-30 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YEs',
        ),
    ]
